### PR TITLE
[FINISHED] SK Unc0ver

### PR DESCRIPTION
**Pull request by DogeTheDogYT**
Created by DogeTheDogYT, I am translating these files for Unc0ver Jailbreak and the Unc0ver team

### CODE REVIEW

**Comment by DogeTheDogYT** [comment]
Sorry to bother you but where is the directory or am I putting the files in wrong directory?
 
Thank you

**Comment by DogeTheDogYT** [comment]
And also I’ve started first on Slovak translation because ha100 is doing the same thing as me

Thank you

**Comment by DogeTheDogYT** [comment]
Translations aren’t very perfect

**Comment by DogeTheDogYT** [comment]
Done it is finished

**Comment by DogeTheDogYT** [comment]
Everything is ready for upload, but translations couldn't be translated better I tried my best with all of them.

Thank you

**Comment by Samgisaninja** [comment]
Thanks for your assistance

**Pull request merged**
